# Generated by Django 5.1.1 on 2024-09-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='C_birthdate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='C_city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='C_gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='C_zipcode',
        ),
    ]
