# Generated by Django 5.1.1 on 2024-10-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customer_c_birthdate_remove_customer_c_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='CAdminID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.catering_admin'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='CAdminID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.catering_admin'),
        ),
        migrations.AlterField(
            model_name='order',
            name='packID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.pack'),
        ),
    ]
