# Generated by Django 5.1.1 on 2024-10-01 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_food_cadminid_alter_order_cadminid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='DAdminID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.delivery_admin'),
        ),
    ]
